name = "hono-demo"
main = "src/index.ts"
compatibility_date = "2024-11-02"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "KV_STORE"
id = "7752376fb2964b838d339845ece9fc69"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "hono-demo"
database_id = "7f839471-d0ec-4fa6-bbad-e0b69dd83970"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1